#!/usr/bin/env node

import chalk from 'chalk'
import split2 from 'split2'
import { execSync } from 'node:child_process'

process.stdin.setEncoding('utf-8');

const memo = {};

process.stdin
  .pipe(split2())
  .on('data', (chunk) => {
    const [year, month, date] = chunk.split('-')
    const key = `${year}-${month}`
    memo[key] = memo[key] || [];
    memo[key] = memo[key].concat([Number(date).toString()])
  });

process.stdin.on('end', () => {
  Object.entries(memo)
    .map((entry) => {
      const year = entry[0].split('-')[0];
      const month = entry[0].split('-')[1];
      const dates = entry[1];
      return {
        year: year,
        month: month,
        dates: dates
      }
    })
    .forEach((page) => {
      printHighlighted(page)
    });
});

const printHighlighted = (page) => {
  let lines = execSync(`cal -h ${page.month} ${page.year}`, {
    encoding: 'utf-8'
  }).split('\n');
  const header = lines.slice(0,2).join('\n');
  const weeks = lines.slice(2);
  console.log(header);
  weeks.forEach((week) => {
    page.dates.forEach((date) => {
      date = date.length == 1 ? ' ' + date : date;
      if(week.includes(date+' ')) {
        const [before, after] = week.split(date+' ')
        week= before + chalk.yellow(date) + ' ' + after;
      }
    });
    process.stdout.write(week + '\n', 'utf-8');
  });
}
